# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebda8ffd74caaf7e860291330da8818ab10e14b7dfb142e10b5f9e1c191e7d4765425c134a42b0ae7807a50f04378278df0c222637e3fc9079993d97ed3c8be7

test:
  secret_key_base: 13e1590528173c83eec770dcb18cf0d979fece4410a7adaecaa22c6f4daa77389470ea1c0c9a9967d6977ddfc50cf117cd80da80d8ca43f37800d6ecae45109f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
